name: Periodic health check
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.2
        with:
          # Check the following URLs one by one sequentially
          url: https://full-stack-open-pokedex.herokuapp.com/
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: no # Optional, defaults to "no"
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 86400s # Optional, only applicable to max-attempts > 1